global:
  token: ABCDEFgH.IJK_LMNOPQER
  prefix: '!'
  # Users that can use commands (also whitelisted)
  mods: ['95286900801146880', '125367104336691200']
  # Users to not moderate
  whitelist: ['81440962496172032']
  # Restrict how many messages a user can send
  slow_mode:
    enabled: false
    time: 1000   # Milliseconds between messages (seconds * 1000)
  # Stop caps spam
  caps_removal:
    enabled: false
    threshold: 10  # Max amount of caps in a row in a message
  # Stop links from being posted in chat
  block_links:
    enabled: false
    invites_only: false   # Only delete discord invites
    allow_non_embed: true # Allow links wrapped in <> that don't show a preview
  # Stop messages with certain words from being posted (put all words/phrases in lowercase)
  blacklisted_words: ['kill your self', 'faggot']
  # Stop mention spam
  mentions_spam:
    enabled: true
    threshold: 10   # If the message has this many mentions or more
    action: 'kick'  # One of: delete, kick, ban
  # Stop repeat messages
  repeat_spam:
    enabled: false
    ignore_case: true   # Ignores capital or lowercase
# Specific channel settings
148656206867726336:
  slow_mode:
    enabled: true
    time: 5000
  blacklisted_words: []
237223871563038720:
  caps_removal:
    enabled: true
    threshold: 10
