name: eirene
description: A chat moderation bot for Discord
version: 0.1.0
author: brussell98
dependencies:
  discord:
    git:
      url: git://github.com/Hackzzila/Discord-Dart.git
      ref: indev
  yaml:
