name: ayaka
description: A chat moderation bot for Discord
version: 1.2.0
author: brussell98
dependencies:
  discord:
    git:
      url: git://github.com/Hackzzila/Discord-Dart.git
      ref: indev
  toml: ^0.5.0
